#!/bin/bash

function run {
 if ! pgrep $1 ;
  then
    $@&
  fi
}

# Set display from arandr saved script
#sh ~/.screenlayout/monitor.sh &

run "xrandr --output DVI-D-0 --off --output HDMI-0 --off --output DP-0 --off --output DP-1 --off --output DP-2 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP-3 --off --output DP-4 --mode 1920x1080 --pos 1920x0 --rotate normal --output DP-5 --off"
#run "xrandr --output VGA-1 --primary --mode 1360x768 --pos 0x0 --rotate normal"
#run "xrandr --output HDMI2 --mode 1920x1080 --pos 1920x0 --rotate normal --output HDMI1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output VIRTUAL1 --off"
#run xrandr --output eDP-1 --primary --mode 1368x768 --pos 0x0 --rotate normal --output DP-1 --off --output HDMI-1 --off --output DP-2 --off --output HDMI-2 --off
#run xrandr --output LVDS1 --mode 1366x768 --output DP3 --mode 1920x1080 --right-of LVDS1
#run xrandr --output DVI-I-0 --right-of HDMI-0 --auto
#run xrandr --output DVI-1 --right-of DVI-0 --auto
#run xrandr --output DVI-D-1 --right-of DVI-I-1 --auto
#run xrandr --output HDMI2 --right-of HDMI1 --auto
#autorandr horizontal

run pamac-tray
run nm-applet
run volumeicon
#run xfce4-power-manager
#run /usr/lib/xfce4/notifyd/xfce4-notifyd
#run /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
run /usr/bin/lxpolkit
run "numlockx on"

dex -a

run sxhkd -c ~/.config/dusk/sxhkd/sxhkdrc-dusk
#run "nitrogen --restore"

#run "insync start"
#run "spotify"
#run "ckb-next -b"
#run "discord"
#run "telegram-desktop"

feh --bg-fill ~/.config/dusk/wallpaper/wallpaper.jpg
#feh --no-xinerama --no-fehbg --bg-scale ~/.config/dusk/wallpaper/otis.png

if pgrep -x "picom" > /dev/null
then
	killall picom
	sleep 1
	picom -b --config $HOME/.config/dusk/picom.conf
else
	picom -b --config $HOME/.config/dusk/picom.conf
fi


